import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import MoneSys
import "../components"
import "../Utils.js" as Utils
ColumnLayout {
    anchors.fill:parent; anchors.margins:16; spacing:12
    RowLayout{Layout.fillWidth:true;Text{text:qsTr("NETWORK");color:Theme.accent;font.pixelSize:10;font.letterSpacing:1.4}Item{Layout.fillWidth:true}Text{text:"RX "+Utils.rate(app.aggregateRxRate)+"   TX "+Utils.rate(app.aggregateTxRate);color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:11}}
    RowLayout{Layout.fillWidth:true;Layout.preferredHeight:128;spacing:14;Rectangle{Layout.fillWidth:true;Layout.fillHeight:true;color:Theme.inset;radius:Theme.radiusCard;border.width:1;border.color:Theme.border;HistoryGraph{anchors.fill:parent;anchors.margins:8;samples:app.rxHistory;fixedMax:104857600;scaleMode:app.yScaleMode;fps:app.graphFps}Text{anchors.left:parent.left;anchors.top:parent.top;anchors.margins:10;text:"RX";color:Theme.accent;font.family:Theme.monoFont;font.pixelSize:10}}Rectangle{Layout.fillWidth:true;Layout.fillHeight:true;color:Theme.inset;radius:Theme.radiusCard;border.width:1;border.color:Theme.border;HistoryGraph{anchors.fill:parent;anchors.margins:8;samples:app.txHistory;fixedMax:104857600;scaleMode:app.yScaleMode;fps:app.graphFps;lineColor:Theme.neutralRamp[3];fillColor:Qt.rgba(0.7,0.72,0.79,0.10)}Text{anchors.left:parent.left;anchors.top:parent.top;anchors.margins:10;text:"TX";color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}}}
    TabBar{id:tabs;Layout.fillWidth:true;TabButton{text:"RX"}TabButton{text:"TX"}TabButton{text:qsTr("Usage")}}
    StackLayout{Layout.fillWidth:true;Layout.fillHeight:true;currentIndex:tabs.currentIndex
        Rectangle{color:Theme.surface;radius:Theme.radiusCard;border.width:1;border.color:Theme.border;ColumnLayout{anchors.fill:parent;anchors.margins:10;RowLayout{Layout.fillWidth:true;Repeater{model:[qsTr("Interface"),"IPv4","bytes","packets","errs","drop","fifo","frame","compressed","multicast"];Text{required property string modelData;Layout.fillWidth:true;text:modelData;color:Theme.textFaint;font.family:Theme.monoFont;font.pixelSize:9;horizontalAlignment:Text.AlignRight}}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:app.network;clip:true;delegate:Rectangle{width:ListView.view.width;height:30;color:index%2?Qt.rgba(1,1,1,0.018):"transparent";RowLayout{anchors.fill:parent;Repeater{model:[name,ipv4||"—",rxBytes,rxPackets,rxErrors,rxDropped,rxFifo,rxFrame,rxCompressed,rxMulticast];Text{required property var modelData;Layout.fillWidth:true;text:modelData;color:Theme.textSecond;elide:Text.ElideRight;font.family:Theme.monoFont;font.pixelSize:9;horizontalAlignment:Text.AlignRight}}}}}}}
        Rectangle{color:Theme.surface;radius:Theme.radiusCard;border.width:1;border.color:Theme.border;ColumnLayout{anchors.fill:parent;anchors.margins:10;RowLayout{Layout.fillWidth:true;Repeater{model:[qsTr("Interface"),"IPv4","bytes","packets","errs","drop","fifo","colls","carrier","compressed"];Text{required property string modelData;Layout.fillWidth:true;text:modelData;color:Theme.textFaint;font.family:Theme.monoFont;font.pixelSize:9;horizontalAlignment:Text.AlignRight}}}ListView{Layout.fillWidth:true;Layout.fillHeight:true;model:app.network;clip:true;delegate:Rectangle{width:ListView.view.width;height:30;color:index%2?Qt.rgba(1,1,1,0.018):"transparent";RowLayout{anchors.fill:parent;Repeater{model:[name,ipv4||"—",txBytes,txPackets,txErrors,txDropped,txFifo,txCollisions,txCarrier,txCompressed];Text{required property var modelData;Layout.fillWidth:true;text:modelData;color:Theme.textSecond;elide:Text.ElideRight;font.family:Theme.monoFont;font.pixelSize:9;horizontalAlignment:Text.AlignRight}}}}}}}
        Rectangle{color:Theme.surface;radius:Theme.radiusCard;border.width:1;border.color:Theme.border;ListView{anchors.fill:parent;anchors.margins:14;model:app.network;spacing:12;clip:true;delegate:ColumnLayout{width:ListView.view.width;spacing:5;RowLayout{Layout.fillWidth:true;Text{text:name+(ipv4?" · "+ipv4:"");color:Theme.textBright;font.pixelSize:12;Layout.fillWidth:true}Text{text:"RX "+Utils.bytes(rxBytes)+" · TX "+Utils.bytes(txBytes);color:Theme.textMuted;font.family:Theme.monoFont;font.pixelSize:10}}ProgressBar{Layout.fillWidth:true;from:0;to:2147483648;value:Math.min(2147483648,rxBytes)}Text{text:qsTr("0 GB → 2 GB visual range · current RX ")+Utils.bytes(rxBytes);color:Theme.textFaint;font.family:Theme.monoFont;font.pixelSize:9}}}}
    }
}
