import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
import MoneSys
import "../Utils.js" as Utils
RowLayout {
    anchors.fill:parent; anchors.margins:16; spacing:12
    ColumnLayout { Layout.fillWidth:true; Layout.fillHeight:true; spacing:10
        RowLayout{Layout.fillWidth:true;Text{text:qsTr("PROCESSES");color:Theme.accent;font.pixelSize:10;font.letterSpacing:1.4}Item{Layout.fillWidth:true}TextField{Layout.preferredWidth:260;placeholderText:qsTr("Filter by name, PID, user, command…");onTextChanged:app.processes.filter=text}Button{text:qsTr("Clear selection");onClicked:app.processes.clearSelection()}}
        Rectangle { Layout.fillWidth:true;Layout.fillHeight:true;color:Theme.surface;radius:Theme.radiusCard;border.width:1;border.color:Theme.border
            ColumnLayout { anchors.fill:parent;anchors.margins:8;spacing:0
                RowLayout{Layout.fillWidth:true;Layout.preferredHeight:28;Text{Layout.fillWidth:true;Layout.minimumWidth:210;text:qsTr("NAME");color:Theme.textFaint;font.pixelSize:9}Text{Layout.preferredWidth:62;text:"PID";color:Theme.textFaint;font.pixelSize:9;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:68;text:"CPU";color:Theme.textFaint;font.pixelSize:9;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:72;text:qsTr("MEM");color:Theme.textFaint;font.pixelSize:9;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:92;text:qsTr("DISK");color:Theme.textFaint;font.pixelSize:9;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:58;text:qsTr("THR");color:Theme.textFaint;font.pixelSize:9;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:98;text:qsTr("STATE");color:Theme.textFaint;font.pixelSize:9}Text{Layout.preferredWidth:105;text:qsTr("USER");color:Theme.textFaint;font.pixelSize:9}}
                ListView { Layout.fillWidth:true;Layout.fillHeight:true;model:app.processes;clip:true;delegate:Rectangle{id:row;width:ListView.view.width;height:31;color:selected?Qt.rgba(0.57,0.52,0.85,0.16):hover.containsMouse?Qt.rgba(1,1,1,0.04):"transparent";RowLayout{anchors.fill:parent;anchors.leftMargin:6;anchors.rightMargin:6;spacing:6;Text{Layout.fillWidth:true;Layout.minimumWidth:210;leftPadding:depth*10;text:(depth>0?"↳ ":"")+name;color:Theme.textBright;elide:Text.ElideRight;font.pixelSize:11}Text{Layout.preferredWidth:62;text:pid;color:Theme.textFaint;font.family:Theme.monoFont;font.pixelSize:10;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:68;text:Number(cpu).toFixed(1)+"%";color:cpu>100?Theme.accentStep(200):Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:72;text:Number(memory).toFixed(1)+"%";color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:92;text:Utils.bytes(readBytes+writeBytes);color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:58;text:threads;color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10;horizontalAlignment:Text.AlignRight}Text{Layout.preferredWidth:98;text:state;color:Theme.textMuted;font.pixelSize:10;elide:Text.ElideRight}Text{Layout.preferredWidth:105;text:user;color:Theme.textMuted;font.pixelSize:10;elide:Text.ElideRight}}MouseArea{id:hover;anchors.fill:parent;hoverEnabled:true;onClicked:app.processes.toggleSelected(index)}} }
            }
        }
    }
    Rectangle { Layout.preferredWidth:Theme.detailW;Layout.fillHeight:true;color:Theme.sidebar;radius:Theme.radiusCard;border.width:1;border.color:Theme.border;property var p:app.processes.selectedProcess
        ColumnLayout{anchors.fill:parent;anchors.margins:14;spacing:9;Text{text:parent.parent.p.name||qsTr("No process selected");color:Theme.textBright;font.pixelSize:17;Layout.fillWidth:true;elide:Text.ElideRight}Text{text:parent.parent.p.pid?"PID "+parent.parent.p.pid+" · PPID "+parent.parent.p.parentPid:"";color:Theme.textFaint;font.family:Theme.monoFont;font.pixelSize:10}Rectangle{Layout.fillWidth:true;height:1;color:Theme.separator}Text{text:parent.parent.p.commandLine||"—";color:Theme.textSecond;wrapMode:Text.WrapAnywhere;Layout.fillWidth:true;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"CPU      "+(parent.parent.p.cpu!==undefined?Number(parent.parent.p.cpu).toFixed(1)+"%":"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"RSS      "+(parent.parent.p.rss!==undefined?Utils.bytes(parent.parent.p.rss):"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"VIRT     "+(parent.parent.p.virtualMemory!==undefined?Utils.bytes(parent.parent.p.virtualMemory):"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"threads  "+(parent.parent.p.threads!==undefined?parent.parent.p.threads:"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"state    "+(parent.parent.p.state||"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"user     "+(parent.parent.p.user||"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"read     "+(parent.parent.p.readBytes!==undefined?Utils.bytes(parent.parent.p.readBytes):"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:"write    "+(parent.parent.p.writeBytes!==undefined?Utils.bytes(parent.parent.p.writeBytes):"—");color:Theme.textSecond;font.family:Theme.monoFont;font.pixelSize:10}Text{text:parent.parent.p.cgroup||"";visible:text.length>0;color:Theme.textFaint;wrapMode:Text.WrapAnywhere;Layout.fillWidth:true;font.family:Theme.monoFont;font.pixelSize:9}Item{Layout.fillHeight:true}Text{text:qsTr("Click rows to multi-select. Selection survives filtering and refreshes while the PID exists.");color:Theme.textFaint;wrapMode:Text.WordWrap;Layout.fillWidth:true;font.pixelSize:10}}
    }
}
